name: CI

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - board: jetson-nano
            revision: 200

    env:
      JETSON_ROOTFS_DIR: /tmp/jetson-builder/rootfs
      JETSON_BUILD_DIR: /tmp/jetson-builder/build
      JETSON_NANO_BOARD: ${{ matrix.board }}
      JETSON_NANO_REVISION: ${{ matrix.revision }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        
      - uses: docker/build-push-action@v2
        with:
          push: false
          tags: jetson-nano-image:latest
          platforms: linux/arm64
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Export rootfs
        run: |
          docker export $(docker create --name nano-rootfs --platform linux/arm64 jetson-nano-image) -o rootfs.tar
          docker rm nano-rootfs
          mkdir -p /tmp/jetson-builder/rootfs
          sudo tar --same-owner -xf rootfs.tar -C /tmp/jetson-builder/rootfs

      - name: Create jetson.img
        run: |
          sudo apt install -y libxml2-utils
          sudo -E ./create-image.sh

      - name: Upload image
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.board }}-r${{ matrix.revision }}
          path: |
            jetson.img
